version: "2"
services:
  web:
    build: .
    image: webapp
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - migration
  migration:
    image: webapp
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  frontend:
    build: ./angular
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - "./angular:/usr/src/app"

volumes:
  redisdata:
