version: "2"
services:
  web:
    build: .
    image: imgweb
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - migration
  migration:
    image: imgweb
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
