# Generated by Django 2.1.1 on 2018-09-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('defaultstatus', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_order', models.IntegerField(blank=True, null=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Applications')),
            ],
            options={
                'db_table': 'userapps',
                'managed': True,
            },
        ),
    ]
